### ISSUE TITLE
Make message customizable

### ISSUE THREAD

**Issue by EchterAgo** [bchtips/bchtips#1]
It would be nice to be able to specify a template for the "I sent you a tip of" message to customize it.

**Comment by bchtips** [comment]
[Done](https://github.com/bchtips/bchtips/commit/626635feec4838bdf8459ee44d057aab7d5cb538)

**Comment by EchterAgo** [comment]
Thanks!

@bchtips @chaintip

**Comment by chaintip** [comment]
@bchtips, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4xgtyl0rweyl2xxyfdq74jdv7s6szec4xvja) `0.01 BCH`| `~   8.92 USD` by @EchterAgo. Please [claim it!](http://www.chaintip.org/#claim)

**Comment by bchtips** [comment]
Thank you :D

**Comment by bchtips** [comment]
bitcoincash:qrujmp38nnrwa0pwte0gcl8wnydwgpf3es8v523sl3
